config/routes.rb
Metube::Application.routes.draw do
  root "videos#show_all"  #look at line 9. This refers to the Views/Folder not the as:

  #       ACTUAL URL               VIEWS FOLDER                           #Named Route (/pages/week-4/rails-intro-routes)
  get "/videos/gladiator"       => "videos#show_gladiator",       as: 'gladiator_video'
  get "/videos/air_force_one"   => 'videos#show_air_force_one',   as: 'air_force_one_sucks'
  get '/videos/fight_club'      => 'videos#show_fight_club',      as: 'fight_club_video'
  get '/videos/dumb_and_dumber' => 'videos#show_dumb_and_dumber', as: 'dumb_and_dumber_video'
  get '/videos/all'             => 'videos#show_all',             as: 'show_all_video'

  get 'posts/atlanta'           => 'posts#atlanta'
  get 'posts/minneapolis'       => 'posts#minneapolis'
  #get "<some_url>" => "<controller_name>#<method_name>"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def atlanta
	end

	def minneapolis
	end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def show_gladiator
		# because of the name of the method
		# this method automatically send the 
		# user to a page with the name 'show_gladiatior'
		# @title = "Are you not entertained?"
		# @description = "I am so not entertained."
		#without defining the instance variable, the page will still render, but will not show the intented variable's value. 
		@video = {
			:title => "Gladiator",
			:description => "This is when Russell Crowe shows he is the man",
			:youtube_id => "FI1ylg4GKv8"
			# :youtube_url => ""
		}
	end

	def show_air_force_one
		@video_crap = {
			:title 				=> "Air Force One",
			:description	=> "a movie about planes and things",
			:youtube_id		=> "dQw4w9WgXcQ"
		}

	end

	def show_fight_club
	end

	def show_dumb_and_dumber
		@video = {
			:title => "Dumb & Dumber",
			:description => "a film of my formative youth.",
			:youtube_id => "S4f4EsPBvTk"
		}
	end

	def show_all
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metube</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/atlanta.erb
<h1>Atlanta</h1>
<h2>The City Too Busy to Care</h2>
<img src='http://t2.gstatic.com/images?q=tbn:ANd9GcSg19D84gIpBRzyDzwQTqfvXuuxmSEkTMSjtyJ9H7MuGXu7MJ5b'</img>

app/views/posts/minneapolis.erb
<h1>Minneapolis</h1>
<img src='http://7minutemiles.com/wp-content/uploads/2011/09/LakeHarrietBandshell-850x634.jpg'>

app/views/videos/show_air_force_one.erb
<h1><%=@video_crap[:title]%></h1>



<iframe width="420" height="315" src="//www.youtube.com/embed/<%=@video_crap[:youtube_id]%>" frameborder="0" allowfullscreen></iframe>


<p><%=@video_crap[:description]%></p>

app/views/videos/show_all.erb
<ul>Some Good Movies and Some Shitty Movies and Some Rick Astley
	<li><%= link_to "Gladiator",  gladiator_video_path %>
	<li><%= link_to "Big Fish",   fight_club_video_path  %>
	<li><%= link_to "Air Force",  air_force_one_sucks_path %>
	<li><%= link_to "OUR PETS HEADS ARE FALLING OFF", dumb_and_dumber_video_path %>

</ul>

app/views/videos/show_dumb_and_dumber.erb
<h1><%= @video[:title] %> </h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%=@video[:youtube_id]%>" frameborder="0" allowfullscreen></iframe>
<p><%= @video[:description] %> </p>

app/views/videos/show_fight_club.html.erb
<h1>BIG FISH</h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/M3YVTgTl-F0" frameborder="0" allowfullscreen></iframe>

<!-- <iframe width="420" height="315" src="//www.youtube.com/embed/FI1ylg4GKv8" frameborder="0" allowfullscreen></iframe> -->

app/views/videos/show_gladiator.html.erb
<h1><%= @video[:title] %></h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video[:youtube_id] %>" frameborder="0" allowfullscreen></iframe>

<p>	<%= @video[:description] %> </p>